brazil_forestry_emissions:
  id: brazil_forestry_emissions
  name: Deforestation rate
  description: Deforestation declined rapidly, particularly after major policy changes in 2004 and again in 2008.
  table: deforestation_rate_copy_test_matallo
  x_axis: date_processed
  type: line
  series:
    deforestation_rate:
      name: Deforestation rate
      column: units_km2_year
      units: km^2/year
      class: line
      y_min: 3000
      y_max: 30000
      strokeColor: 'rgba(238,87,41,1)'

brazil_forestry_emission_drivers:
  id: brazil_forestry_emission_drivers
  name: Commodity Prices
  description: Common drivers of deforestation, such as commodity prices, and land protection appear to have changed deforestation patterns, with large scale deforestation declining much more rapidly than small scale (e.g. tracts of less than 25 hectares).
  table: commodity_prices_copy_test_matallo
  x_axis: date_processed
  type: line
  series:
    corn:
      name: Corn price
      column: corn
      units: BRL/Ton
      class: line
      y_min: 0
      y_max: 1500
      strokeColor: 'rgba(238,87,41,1)'
    soybean:
      name: Soybean price
      column: soybeans
      units: BRL/Ton
      class: line
      y_min: 0
      y_max: 1500
      strokeColor: 'rgba(79,110,191,1)'

brazil_forestry_emission_drivers_2:
  id: brazil_forestry_emission_drivers_2
  name: Deforestation polygons indicator
  description: Common drivers of deforestation, such as commodity prices, and land protection appear to have changed deforestation patterns, with large scale deforestation declining much more rapidly than small scale (e.g. tracts of less than 25 hectares).
  table: deforestation_polygons_ind_copy_test_matallo
  x_axis: date_processed
  type: line
  series:
    _25_hectares:
      name: < 25 Hectares
      column: _25_hectares
      units: Index (2004=100)
      class: line
      y_min: -20
      y_max: 180
      strokeColor: 'rgba(238,87,41,1)'
    _25_100_hectares:
      name: 25-100 Hectares
      column: _25_100_hectares
      units: Index (2004=100)
      class: line
      y_min: -20
      y_max: 180
      strokeColor: "#F0542C"
    _100_500_hectares:
      name: 100-500 Hectares
      column: _100_500_hectares
      units: Index (2004=100)
      class: line
      y_min: -20
      y_max: 180
      strokeColor: "#00D9A3"
    _500_1000_hectares:
      name: 500-1000 Hectares
      column: _500_1000_hectares
      units: Index (2004=100)
      class: line
      y_min: -20
      y_max: 180
      strokeColor: "#FFD24D"
    _1000_hectares:
      name: '> 1000 Hectares'
      column: _1000_hectares
      units: Index (2004=100)
      class: line
      y_min: -20
      y_max: 180
      strokeColor: "#E599FF"

brazil_forestry_policy:
  id: brazil_forestry_policy
  name: Protected Lands
  description: As an example of increased Brazilian policy efforts, Brazil has increased efforts to reduce deforestation, and the amount of land under government protection has increased significantly since 2001.
  table: protected_lands_copy_test_matallo
  x_axis: date_processed
  type: line
  series:
    methane_mmtco2e:
      name: Integral Protection
      column: integral_protection
      units: K km<sup>2</sup>
      class: area
      y_min: 0
      y_max: 1200
      strokeColor: 'rgba(238,87,41,1)'
      fillColor: 'rgba(238,87,41,0.2)'
    nitrous_oxide_mmtco2e:
      name: Sustainable Use
      column: sustainable_use
      units: K km<sup>2</sup>
      class: area
      y_min: 0
      y_max: 1200
      strokeColor: 'rgba(79,110,191,1)'
      fillColor: 'rgba(79,110,191,0.2)'

brazil_agriculture_emissions:
  id: brazil_agriculture_emissions
  table: land_use_emissions_copy_test_matallo
  name: Emissions
  description: Both land under cultivation and non-CO2 emissions increased.
  x_axis: date_processed
  type: line
  series:
    methane_mmtco2e:
      name: Methane
      column: methane_mmtco2e
      units: MTn CO2e
      class: line
      y_min: 70
      y_max: 350
      strokeColor: 'rgba(238,87,41,1)'
    nitrous_oxide_mmtco2e:
      name: Nitrous Oxide
      column: nitrous_oxide_mmtco2e
      units: MTn CO2e
      class: line
      y_min: 70
      y_max: 350
      strokeColor: 'rgba(79,110,191,1)'

brazil_agriculture_emissions_2:
  id: brazil_agriculture_emissions_2
  name: Land Use
  table: land_use_emissions_copy_test_matallo
  description: Both land under cultivation and non-CO2 emissions increased.
  x_axis: date_processed
  type: line
  series:
    land_use_million_hectares:
      name: Land Use
      column: land_use_million_hectares
      units: million hectares
      class: line
      y_min: 35
      y_max: 70
      strokeColor: 'rgba(238,87,41,1)'

brazil_agriculture_emission_drivers:
  id: brazil_agriculture_emission_drivers
  name: Intensity indices
  table: emissions_drivers_copy_test_matallo
  description: Although the intensity of food production per hectare increased, mechanization did not increase.
  x_axis: date_processed
  type: line
  series:
    food:
      name: Food
      column: food_production_per_hectare
      units: Index (1980=100)
      class: line
      y_min: 50
      y_max: 300
      strokeColor: "#546DBC"
    livestock:
      name: Livestock
      column: livestock_production_per_hectare
      units: Index (1980=100)      
      class: line
      y_min: 50
      y_max: 300
      strokeColor: "#F0542C"
    non_food:
      name: Non-food
      column: non_food_production_per_hectare
      units: Index (1980=100)      
      class: line
      y_min: 50
      y_max: 300
      strokeColor: '#00D9A3'
    tractor:
      name: Tractor usage
      column: tractor_usage_per_hectare
      units: Index (1980=100)
      class: line
      y_min: 50
      y_max: 300
      strokeColor: '#FFD24D'

brazil_agriculture_emission_drivers_2:
  id: brazil_agriculture_emission_drivers_2
  name: Exports
  table: brazil_ag_2_exports_copy_test_matallo
  description: Increasing land use, some of which satisfied export growth, and some of which satisfied population growth (not shown), was a major driver of growing emissions.
  x_axis: date_processed
  type: line
  series:
    raw_materials:
      name: Agricultural raw materials
      column: agricultural_raw_materials
      units: B USD
      class: line
      y_min: -10
      y_max: 55
      strokeColor: "#546DBC"
    food:
      name: Food
      column: food
      units: B USD
      class: line
      y_min: -10
      y_max: 55
      strokeColor: "#F0542C"

brazil_agriculture_policy:
  id: brazil_agriculture_policy
  name: Credit
  table: brazil_ag_3_credit_subsidies_copy_test_matallo
  description: Brazil made increasing the productivity of agricultural land a priority as a means to reduce expansion into new land and deforestation. Subsidies to producers, in part to modernize their operations, steadily increased over time. In the 1990s, credit subsidies were offset by price controls set below market prices; as these price controls rose above market prices, they became additional effective subsidies.
  description_long: long
  x_axis: date_processed
  type: line
  series:
    credit:
      name: Credit Subsidies
      column: credit_subsidies
      units: MM BRL
      class: line
      y_min: -7000
      y_max: 18000
      strokeColor: "#546DBC"
    non_credit:
      name: Non-Credit Subsidies
      column: non_credit_producer_subsidies
      units: MM BRL
      class: line
      y_min: -7000
      y_max: 18000
      strokeColor: "#F0542C"
    total:
      name: Total Subsidies to Producers
      column: total_producer_support
      units: MM BRL
      class: line
      y_min: -7000
      y_max: 18000
      strokeColor: "#00D9A3"

# ---------------------------------------------------

us_buildings_emissions:
  id: us_buildings_emissions
  name: Emissions
  table: emissions_mmtco2e_copy_test_matallo
  description: Emissions grew slowly, but steadily, until 2005, when emissions peaked and slowly declined.
  x_axis: date_processed
  type: line
  series:
    commercial:
      name: Commercial
      column: commercial
      units: MM T CO²
      class: line
      y_min: 0
      y_max: 2000
      strokeColor: "rgba(238,87,41,1)"
    residential:
      name: Residential
      column: residential
      units: MM T CO²
      class: line
      y_min: 0
      y_max: 2000
      strokeColor: "rgba(79,110,191,1)" 

us_buildings_emissions_2:
  id: us_buildings_emissions_2
  name: Floorspace
  table: buildings_floorspace_billion_square_meters_copy_test_matallo
  description: Total building stock, as reflected by total floor space statistics, grew steadily, while the increase in residential floor space between 1995 and 2005 was particularly noteworthy.
  x_axis: date_processed
  type: line
  series:
    commercial:
      name: Commercial
      column: commercial
      units: "B m<sup>2</sup>"
      class: line
      y_min: 0
      y_max: 25
      strokeColor: "rgba(238,87,41,1)"
    residential:
      name: Residential
      column: residential
      units: "B m<sup>2</sup>"
      class: line
      y_min: 0
      y_max: 25
      strokeColor: "rgba(79,110,191,1)" 

us_buildings_emissions_drivers:
  id: us_buildings_emission_drivers
  name: Building Drivers
  table: changes_in_emissions_drivers_copy_test_matallo
  description: Growth in population and floor space per person were the largest drivers of buildings emissions. In the late 2000’s, energy efficiency gains, particularly in residential heating and cooling caught up with slowing floor space growth.
  description_long: longest
  type: bars
  units: "Million T CO²"
  name_column: variable
  x_groups:
    0:
      label: Commercial
      column: commercial
    1:
      label: Residential
      column: residential

us_buildings_policy:
  id: us_buildings_policy
  name: Energy efficiency spending
  table: energy_efficiency_spending_copy_test_matallo
  description: Efficiency spending by federal and local governments increased over the last decade, with a spike due to the 2009 stimulus.
  x_axis: date_processed
  type: line
  series:
    energy_efficiency_dsm_spending:
      name: Energy Efficiency DSM Spending
      column: energy_efficiency_dsm_spending
      units: MM USD
      class: line
      y_min: -5000
      y_max: 27500
      strokeColor: "rgba(238,87,41,1)"
    federal_expenditures:
      name: Federal expenditures
      column: federal_expenditures
      units: MM USD
      class: line
      y_min: -5000
      y_max: 27500
      strokeColor: "rgba(79,110,191,1)" 

us_buildings_policy_2:
  id: us_buildings_policy_2
  name: Building codes
  table: code_building_energy_intensity_index_copy_test_matallo
  description: Building codes tightened steadily - particularly for commercial buildings where the federal government played a larger role.
  x_axis: date_processed
  type: line
  series:
    commercial:
      name: Commercial
      column: commercial
      units: Index (1990=100)
      class: line
      y_min: 40
      y_max: 150
      strokeColor: "rgba(238,87,41,1)"
    residential:
      name: Residential
      column: residential
      units: Index (1990=100)
      class: line
      y_min: 40
      y_max: 150
      strokeColor: "rgba(79,110,191,1)" 
